---

stages:
  - build
  - deploy

build:
  stage: build
  except:
    - tags
  image: frankhjung/haskell:9.2.8
  variables:
    PROJECT: Robot
    RTSOPTS: "+RTS -N1 -s"
    STACK_ROOT: ${CI_PROJECT_DIR}/.stack
  script:
    - make clean check build test doc
    - mv $(stack path --local-doc-root)/${PROJECT}*/ public/
    - make exec
  artifacts:
    paths:
      - public
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .stack-work/

pages:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
  image: alpine:latest
  script:
    - echo Publishing documentation ...
  dependencies:
    - build
  artifacts:
    paths:
      - public
