image:
  name: haskell:8.2.2
  entrypoint: [""]

stages:
  - all

variables:
  STACK_ROOT: "${CI_PROJECT_DIR}/.stack"

cache:
  key: robot-cache
  paths:
    - .stack
    - .stack-work

all:
  stage: all
  script:
    - make setup
    - make build
    - make test
    - make exec
