---

stages:
  - build
  - deploy

variables:
  TARGET: robot
  RTSOPTS: "+RTS -N1"
  STACK_ROOT: ${CI_PROJECT_DIR}/.stack

build:
  except:
    - tags
  image:
    name: frankhjung/haskell:8.8.4
    entrypoint: [""]
  stage: build
  script:
    - make setup clean check build test doc exec
    - mv $(stack path --local-doc-root)/robot*/ public/
  artifacts:
    paths:
      - public
  cache:
    key: ${CI_COMMIT_REF_NAME}
    paths:
      - .stack
      - .stack-work

pages:
  only:
    refs:
      - master
  image: alpine:latest
  stage: deploy
  script:
    - echo Publishing pages ...
  dependencies:
    - build
  artifacts:
    paths:
      - public
