---

stages:
  - build
  - deploy

variables:
  PROJECT: robot
  RTSOPTS: "+RTS -N1"
  STACK_ROOT: ${CI_PROJECT_DIR}/.stack

build:
  stage: build
  except:
    - tags
  image: frankhjung/haskell:9.0.2
  variables:
    STACK_ROOT: ${CI_PROJECT_DIR}/.stack
  script:
    - make clean check build test doc exec
    - mv dist-newstyle/build/x86_64-linux/ghc-9.0.2/${PROJECT}-*/doc/html/${PROJECT}/ public/
  artifacts:
    paths:
      - public
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .stack/
      - .stack-work/

pages:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
  image: alpine:latest
  script:
    - echo Publishing documentation ...
  dependencies:
    - build
  artifacts:
    paths:
      - public
