image: fpco/stack-build:lts-11.17

stages:
  - all

variables:
  STACK_ROOT: "${CI_PROJECT_DIR}/.stack"

cache:
  key: robot-cache
  paths:
    - .stack
    - .stack-work

all:
  stage: all
  script:
    - make setup
    - make build
    - make test
    - make exec
